### ISSUE TITLE
SVN status warning in update function

### ISSUE THREAD

**Issue by iandunn** [markjaquith/WPPlugin#1]
I'm getting these warnings when running the update command:

> [ian@audrey plugins]$ wpplugin update vip-scanner
> svn: Try 'svn help' for more info
> svn: Not enough arguments provided
> [ian@audrey plugins]$ wpplugin update theme-check
> svn: Try 'svn help' for more info
> svn: Not enough arguments provided

The `remove_files` and `add` functions seem to be completing successfully, though.

**Comment by markjaquith** [comment]
Do you have Subversion 1.7?

## 

Mark Jaquith
• http://markjaquith.com/

**Comment by iandunn** [comment]
1.6.18, the latest available from the Fedora 16 updates repo.

**Comment by iandunn** [comment]
I updated Subversion to 1.7.7, but am getting the same warning:

> [ian@audrey plugins]$ wpplugin update advanced-custom-fields
> svn: E205001: Try 'svn help' for more info
> svn: E205001: Not enough arguments provided

**Comment by markjaquith** [comment]
Can you narrow it down to a specific SVN command?

Also, maybe consider giving [WP-CLI](http://wp-cli.org/) a try. :-) It rather renders this script moot.

**Comment by iandunn** [comment]
Ah, good point. I'd heard great things about wp-cli, but forgot that it can do plugin updates, so I never tried it out. I've been playing with it this morning and it looks like a great solution. Thanks for the tip :)

**Comment by iandunn** [comment]
Closing this because it's old and I'm no longer using WPPlugin.
